### PR TITLE
feat: refactor deployment and add additional props

### PR DESCRIPTION
**Pull request by mmalenic**
Changes related to orcabus deployment.

### Changes - construct
* Refactor the construct definition into functions to make it clearer what components do.
* Add props for a VPC, existing role, and existing httpApi.
    * If an existing role is used, then no role is created and props for adding permissions for secrets/buckets is ignored.
    * If an existing httpApi is used, then no Route53 records, certificates, hosted zones, jwt authorizers, or other stateful resources are created.

### Changes - build
* Add github actions to publish on github release.
* Use pnpm and add `pnpm-lock.yaml`.
* ~~Publish inside the `dist` directory and avoid checking in auto generated `.js` and `.d.ts` files, note the `outDir` inside `tsconfig.json` which controls this.~~ This doesn't work, I've reverted back to building in the root directory instead.
* Add license.

For publishing, no idea if this will work but we'll give it a shot. I think potentially we should transition to using some sort of packaging tool rather than manual `tsc` calls. Jsii or projen probably makes sense given this is a CDK project (could we use deno or bun's nodejs interop and native typescript support to make it simplier as well?). Also, potentially we can use @andrewpatto's existing UMCCR org in npm as well: https://www.npmjs.com/~umccrservice. Although, happy to leave it under our accounts too.

### CODE REVIEW

**Comment by mmalenic** [comment]
This currently publishes manually when a github release is created.

I think we can eventually use something like [release-please](https://github.com/googleapis/release-please?tab=readme-ov-file#strategy-language-types-supported) to have publish automation similar to htsget-rs?

**Comment by brainstorm** [comment]
> For publishing, no idea if this will work but we'll give it a shot. I think potentially we should transition to using some sort of packaging tool rather than manual tsc calls. Jsii or projen probably makes sense given this is a CDK project (could we use deno or bun's nodejs interop and native typescript support to make it simplier as well?). Also, potentially we can use @andrewpatto's existing UMCCR org in npm as well: https://www.npmjs.com/~umccrservice. Although, happy to leave it under our accounts too.

No strong opinions on TS deploy tooling, but remember we didn't have a very pleasant DX w/ `projen` over `cargo-lambda-cdk`? I'd be a bit skeptical to adopt that one, but perhaps we can give it a second change, up to you! :-S

w.r.t to using Patto's NPM org: let's not bother him, probably we'll have to change the UMCCR brand anyway fairly soon, so I'll pass and keep it on our own accts for now?

**Review by brainstorm — APPROVED** [review]
Kudos for those changes! 

I'm not up to speed with `pnpm` over plain `npm` or `yarn`, but for sure you have good reasons :)

**Comment by brainstorm** [comment]
> I think we can eventually use something like [release-please](https://github.com/googleapis/release-please?tab=readme-ov-file#strategy-language-types-supported) to have publish automation similar to htsget-rs?

Totally, yes please! :)

**Comment by mmalenic** [comment]
> No strong opinions on TS deploy tooling, but remember we didn't have a very pleasant DX w/ projen over cargo-lambda-cdk? I'd be a bit skeptical to adopt that one, but perhaps we can give it a second change, up to you! :-S

Fair enough! Unless we are using code bindings for CDK in Go or C# there probably isn't much point. All of our infra is typescript anyway. It might be nice to have the option though for external users though? In which case something like JSII or projen is probably the only thing that makes sense.

> I'm not up to speed with pnpm over plain npm or yarn, but for sure you have good reasons :)

There's no particular reason for this project because it's fairly simply. I've just never used it before so wanted to try. I think it's faster and has better support for things like workspaces.

**Comment by mmalenic** [comment]
Interestingly yarn seems to perform better? https://pnpm.io/benchmarks

**Comment by andrewpatto** [comment]
btw I ended up using `jsii` directly - without having to buy into `projen` world at all.. just launching `jsii` was quite easy (pacmak etc)

**Pull request merged**
